# HPO Configuration File
# Fixed hyperparameters (not searchable)
env: "LunarLander-v3"
model: "ppo"
seed: 42
episodes: 2000
max_steps: 2048
buffer_size: 1000000
device: "cpu"
lr: 3e-4

# SAC specific hyperparameters (fixed)
tau: 0.005

# Rainbow DQN hyperparameters (fixed)
alpha: 0.6
beta_start: 0.4

# Evaluation hyperparameters (fixed)
eval: true
eval_period: 10
eval_episodes: 5

# HPO hyperparameters (fixed)
hpo_n_trials: 10
hpo_study_name: "rl_hyperopt"

# Searchable hyperparameters (default search spaces)
searchable_hyperparameters:
  batch_size: [256]
  gamma: [0.99]
  hidden_dim: [256]
  n_layers: [3]
  # ppo
  ppo_epochs: [3]
  clip_eps: [0.2]
  n_transactions: [1000]
  normalize_advantages: [false] 
  # sac
  start_steps: [1000]
  entropy_coef: [1.0]
  # rainbow_dqn
  target_update: [10]
  # td3
  policy_delay: [2]
  policy_noise: [0.2]
  noise_clip: [0.5]
  exploration_noise: [0.1]