# Training Configuration File - PPO Sequential Models
# Environment settings
env: "BipedalWalkerHardcore-v3"
model:
  model: "ppo_seq"  # Options: ppo, sac, rainbow_dqn, discrete_sac, td3, ppo_seq
  hidden_dim: 256
  n_layers: 2
  embedding_type: "lstm"  # Options: fc, lstm, transformer
  seq_len: 3
  seq_stride: 3  # When > 1: Use strided processing for both LSTM and Transformer

# Training parameters
seed: 42
episodes: 20000
max_steps: 2000
lr: 3e-4
gamma: 0.99
batch_size: 256
start_steps: 10000
n_envs: 2

# Device settings
device: "cpu"  # Options: cpu, cuda

# Evaluation settings
eval: true
eval_period: 10
eval_episodes: 10

# Save settings
save_dir: "results"

# PPO specific parameters
ppo_epochs: 5
clip_eps: 0.2
n_transactions: 20000
normalize_advantages: true
gae: true
gae_lambda: 0.95
max_grad_norm: 0.5