# Training Configuration File for TD3 on BipedalWalker
# Environment settings
env: "BipedalWalkerHardcore-v3"
model:
  model: "td3_seq"
  hidden_dim: 256
  n_layers: 2
  embedding_type: "lstm"  # Options: fc, lstm, transformer
  use_layernorm: true
  seq_len: 10
  seq_stride: 2

buffer:
  buffer_size: 1000000
  buffer_type: "sequential"

# Training parameters
seed: 42
episodes: 5000
max_steps: 2000
lr: 3e-4
gamma: 0.99
batch_size: 256
start_steps: 25000

# Device settings
device: "cpu"  # Options: cpu, cuda

# Evaluation settings
eval: true
eval_period: 10
eval_episodes: 10

# Save settings
save_dir: "results"

# target update interval
target_update_interval: 8000

# TD3 specific parameters
tau: 0.005
policy_delay: 2
policy_noise: 0.2
noise_clip: 0.5
exploration_noise: 0.1 