# Training Configuration File for TD3 on BipedalWalker
# Environment settings
env: "BipedalWalkerHardcore-v3"
model:
  model: "td3_seq"
  hidden_dim: 256
  n_layers: 2
  embedding_type: "lstm"  # Options: fc, lstm, transformer
  use_layernorm: true
  seq_len: 32
  seq_stride: 1

buffer:
  buffer_size: 1000000
  buffer_type: "per_sequential"
  alpha: 0.6
  beta_start: 0.4
  beta_frames: 100000

# Training parameters
seed: 42
episodes: 5000
max_steps: 1600
lr: 3e-4
gamma: 0.99
batch_size: 256
start_steps: 1000
n_envs: 2

# Device settings
device: "cpu"  # Options: cpu, cuda

# Evaluation settings
eval: true
eval_period: 20
eval_episodes: 10

# Save settings
save_dir: "results"

# TD3 specific parameters
tau: 0.005
policy_delay: 2
policy_noise: 0.2
noise_clip: 0.5
exploration_noise: 0.1 